"""Generate challenges/SCOREBOARD.md from a pytest run (vibe 000094).

Runs the challenge suite programmatically, reads each challenge's CHALLENGE
metadata and per-level outcomes, and renders the scoreboard grouped by tier.
The scoreboard is committed; CI regenerates it and fails on any diff, so
`git log challenges/SCOREBOARD.md` is the product-progress record.

Levels per challenge:
  L2 performed — all L2 tests exist and genuinely pass
  L1 verified  — else, all L1 tests exist and genuinely pass
  L0 failing   — anything else (including strict-xfail placeholders)

Usage:  python challenges/make_scoreboard.py [--check]
  --check: exit nonzero if the committed scoreboard is stale (CI mode).
"""

import sys
from collections import defaultdict
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCOREBOARD = ROOT / "challenges" / "SCOREBOARD.md"

sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "python"))

from challenges import harness  # noqa: E402


class _Collector:
    """Pytest plugin: per challenge directory, per level, collect outcomes."""

    def __init__(self):
        self.meta = {}  # challenge dir name -> CHALLENGE dict
        # dir name -> level -> list of True (genuine pass) / False (anything else)
        self.outcomes = defaultdict(lambda: defaultdict(list))
        self._item_info = {}  # nodeid -> (dir name, level)

    def pytest_collection_modifyitems(self, items):
        for item in items:
            challenge_dir = item.path.parent
            if challenge_dir.parent.name != "challenges":
                continue
            name = challenge_dir.name
            self.meta.setdefault(name, getattr(item.module, "CHALLENGE", None))
            marker = item.get_closest_marker("challenge_level")
            level = marker.args[0] if marker else None
            self._item_info[item.nodeid] = (name, level)

    def pytest_runtest_logreport(self, report):
        info = self._item_info.get(report.nodeid)
        if info is None or report.when != "call":
            return
        name, level = info
        genuine_pass = report.passed and not hasattr(report, "wasxfail")
        self.outcomes[name][level].append(genuine_pass)

    def level_of(self, name):
        for lvl in (harness.L2, harness.L1):
            results = self.outcomes[name].get(lvl)
            if results and all(results):
                return lvl
        return "L0"


_BADGE = {
    "L2": "**L2 performed**",
    "L1": "L1 verified",
    "L0": "L0 failing",
}


def _identity_dag_section():
    """The identity DAG, and which challenge discharges each proof obligation.

    tender's library owns the graph; this suite owns the derivations.  Showing
    them together is the point: an identity's trustworthiness is the
    trustworthiness of its derivation, and depth says how far a result stands
    above the axioms.
    """
    import tender.identities as ti

    lines = [
        "## Identity DAG",
        "",
        "Axioms are definitional (no proof obligation); a derived identity "
        "owes a derivation, and `cites` is what that derivation may lean on. "
        "Depth counts steps above the axioms.",
        "",
        "| Identity | Kind | Depth | Rests on | Derived by |",
        "|---|---|---|---|---|",
    ]
    for n in ti.nodes():
        kind = "axiom" if n.kind == ti.AXIOM else "derived"
        depth = "—" if n.kind == ti.AXIOM else str(ti.depth(n.name))
        cites = ", ".join(f"`{c}`" for c in n.cites) or "—"
        if n.kind == ti.AXIOM:
            proof = "—"
        elif n.proof:
            proof = f"challenge {n.proof}"
        else:
            proof = "**not yet derived**"
        lines.append(
            f"| `{n.name}` | {kind} | {depth} | {cites} | {proof} |"
        )
    lines.append("")
    return lines


def render(collector):
    by_tier = defaultdict(list)
    for name in sorted(collector.meta):
        meta = collector.meta[name] or {}
        by_tier[meta.get("tier", "?")].append((name, meta))

    counts = defaultdict(int)
    for name in collector.meta:
        counts[collector.level_of(name)] += 1

    lines = [
        "# Challenge scoreboard",
        "",
        "Generated by `python challenges/make_scoreboard.py` — do not edit by",
        "hand.  Levels: **L2 performed** = direct-notation derivation on the",
        "public surface; L1 verified = endpoint confirmed by component check;",
        "L0 failing = enumerated, not yet reached (strict xfail).",
        "",
        f"**{len(collector.meta)} challenges** — "
        f"{counts['L2']} at L2, {counts['L1']} at L1, {counts['L0']} at L0.",
        "",
    ]
    lines += _identity_dag_section()
    for tier in sorted(by_tier):
        lines += [f"## Tier {tier} — {harness.TIERS.get(tier, 'unknown')}", ""]
        lines += ["| # | Challenge | Level | Source |", "|---|---|---|---|"]
        for name, meta in by_tier[tier]:
            number, _, slug = name.partition("_")
            title = meta.get("title", slug)
            source = meta.get("source") or "—"
            badge = _BADGE[collector.level_of(name)]
            lines.append(f"| {number} | {title} | {badge} | {source} |")
        lines.append("")
    return "\n".join(lines)


def main(argv):
    check = "--check" in argv
    collector = _Collector()
    exit_code = pytest.main(
        ["challenges", "-q", "--no-header", "-p", "no:cacheprovider"],
        plugins=[collector],
    )
    if exit_code not in (0, 1):  # collection error, usage error, interrupted…
        print(f"pytest failed with exit code {exit_code}", file=sys.stderr)
        return int(exit_code)

    content = render(collector)
    if check:
        current = SCOREBOARD.read_text() if SCOREBOARD.exists() else ""
        if current != content:
            print(
                "SCOREBOARD.md is stale — regenerate with "
                "`python challenges/make_scoreboard.py`",
                file=sys.stderr,
            )
            return 1
        print("SCOREBOARD.md is up to date")
        return 0
    SCOREBOARD.write_text(content)
    print(f"Written: {SCOREBOARD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
